language: java
dist: trusty
install: true
sudo: true
jdk: oraclejdk8
addons:
  sonarcloud:
    organization: "kizombadev-github"
    token:
      secure: $SONAR_TOKEN
notifications:
  email: true
before_install:
- chmod +x mvnw
jobs:
  include:
  - stage: "Builds"
  - script: ./mvnw clean verify sonar:sonar -B
    name: "mvn & SonarCloud"