elasticsearch:
  clustername: elasticsearch
  nodes:
  - ip: localhost
    port: 9200
  indexname: eventstudio
extended-analysis:
  eventType: access_log
  indicatorField: ip
  referenceField: link
server:
  port: 8084