elasticsearch:
  clustername: elasticsearch
  nodes:
  - ip: localhost
    port: 9200
  indexname: eventstudio
extended-analysis:
  maxHistoricalEvents: 100
  percentile: 10
  interquartileFactor: 1.5
server:
  port: 8084