extended-analysis:
  eventType: access_log
  indicatorField: ip
  referenceField: link
elasticsearch:
  clustername: elasticsearch
  nodes:
  - ip: localhost
    port: 9300
  indexname: eventstudio
server:
  port: 8084