elasticsearch:
  clustername: elasticsearch
  nodes:
  - ip: localhost
    port: 9200
  indexname: eventstudio
house-keeping:
  maxIndexMbSize: 1024
  repetitionIntervalInMinutes: 1
server:
  port: 8085